#This Rscript generates the input files for the Reddyproc tool
#performs U star filtering first and then,
#It generates final input files for the final gapfilling
#IT ALSO ADDS THE NUMBER OF u STAR FILTERED DATA TO THE fILTER SUMMARY FILES

#################################################
#  1. GENERATING DATASETS FOR Ustar filtering 
# (Reddyproc R package)
#################################################

################
# Code start
##################
# clear memory
rm(list=ls())


#######
# To upload filtered datasets:
# (In case you don't do this step right after generating the SITE_FILTERED files)
##########

  #For BB:
final<-read.csv( paste('./Flux-tower/merged_data/BB_FILTERED','.csv',sep=""),sep=",",header=TRUE,dec=".")

#Adding NEE , 
#Decision: I decided to use the CO2 storage component generated by EDDY pro which is based on one point measurements. 
#Eddy pro offers a value for co2 storage flux i (co2_strg) included in the EDDYPRO full output and it is estimated from co2 concentrations and based on a 1-point profile. 
#More details: https://www.licor.com/env/help/EddyPro5/index.htm#Calculating_Storage_Fluxes.htm?Highlight=STORAGE).More info in 

final$NEE_i<-rowSums(final[,match(c("co2_flux_filtered","co2_strg"),names(final))],na.rm=F)  
final$NEE<- ifelse(final$NEE_i>-50 & final$NEE_i<50 ,final$NEE_i,NA)   #To remove NEE < -50 or NEE>50 AS THIS SITUATION SEEMS PROBLEMATIC OR UNRELIABLE FOR nee PARTITIONING
plot(final$co2_flux_filtered,final$NEE,ylim=c(-100,120),xlim=c(-100,120))
abline(0,1,col='grey',lty=2)
abline(v=-50)
abline(h=-50)

#Study the importance of ch4_flux storage term
# I decided NOT to use ch4 storage. Brenda also did not consider.. following her method..
final$ch4f<-rowSums(final[,match(c("ch4_flux_filtered","ch4_strg"),names(final))],na.rm=F)  
plot(final$ch4_flux_filtered,final$ch4f,ylim=c(-1,1),xlim=c(-1,1))
abline(0,1,col='grey',lty=2)
abline(v=0)
abline(h=0)

#Converting units for the right input file format
final$Tair_Vaisala_C<-ifelse(is.na(final$AIR_TEMP_2M),final$air_temperature-273.15,final$AIR_TEMP_2M)  #Tair from Vaisala and from Li7550 when Vaisala temp is not available 
final$RH_Li<-ifelse(is.na(final$RH),final$RH_2M, final$RH)  #RH from CR1000 except when not availabe, then Licor. #This is because the lICOR seemed to saturate earlier
names(final)[names(final)=="VPD.1"]<- "VPD_2M"

final$VPD_hPa<-ifelse(is.na(final$VPD_2M),final$VPD*0.01 ,10*final$VPD_2M)

names(final)
#Selecting variables

variables<-c('year','jday','hour_dec','NEE',"ch4_flux_filtered",'LE_filtered','H_filtered','SHORTWAVE_IN','Tair_Vaisala_C','SOIL_TEMP_5CM','SOIL_TEMP_10CM','RH_Li','VPD_hPa','u.',"WTH") 

DATA <- final[, match(variables,names(final))]

#################
#Making sure the file starts on time 00:30 doy 1 and ends at midnight (time 0:00) of the last day of the year 

#Tansforming the variables names
names_input<-c('Year','DoY','Hour','NEE','CH4','LE','H','Rg','Tair','Tsoil5cm','Tsoil10cm','rH','VPD','Ustar',"WTH")
names(DATA)<-names_input

#Transforming missing values in -9999:
DATA[is.na(DATA)]<--9999

#Adding the units row:
UNITS<-list('-','-','-','umol_m-2_s-1','umol_m-2_s-1','Wm-2','Wm-2','Wm-2','degC','degC','degC','%','hPa','ms-1','cm')

DATA<-rbind(UNITS,DATA)

head(DATA)

#Saving the file:
write.table(DATA, file = paste('./Flux-tower/merged_data/for_gapfilling','.txt',sep=''),row.names=FALSE,sep='\t')   


